### ISSUE TITLE
Не прикрепляются фотографии к форме сбора данных

### ISSUE THREAD

**Issue by Romchik93** [nextgis/nextgiscollector_android#12]
Кейс:
В коллекторе добавляю в слой новую точку, выбираю фотографию, но она не прикрепляется

Форма имеет несколько вкладок, скорее всего это имеет значение

Проект-коллектор http://romangis.nextgis.com/resource/185
Слой с формой http://romangis.nextgis.com/resource/182

**Comment by Romchik93** [comment]
Ссылка на тикет - https://support.nextgis.com/#ticket/zoom/303

**Comment by 4eRTuk** [comment]
Fixed
