### ISSUE TITLE
Неинтуитивное сообщение о неверное введенном пароле

### ISSUE THREAD

**Issue by eduard-kazakov** [nextgis/nextgiscollector_android#14]
Сообщение гласит "Соединение не установлено", если вводить неправильный пароль. По началу складывается впечатление, что проблема с сетью. 
Можно ли добавить в него ясности и уведомлять пользователя о неверно введенных данных?

**Comment by simgislab** [comment]
Подтверждаю и поддерживаю. В вебе сообщение при вводе неправильного пароля однозначное.

![](http://m-d.me/img/ss/20210312_203247.png)

**Comment by 4eRTuk** [comment]
Добавил обработку, если проблема в кредах. Сообщение стандартное как во многих местах у нас используется: ```Проблема аутентификации```. Поменять формулировку?

**Comment by simgislab** [comment]
Я бы писал также как в вебе "логин или пароль не верны", обычный человек не знает что такое "аутентификация"

**Comment by 4eRTuk** [comment]
Изменил, и в мобильном тоже
