### ISSUE TITLE
Доступ к чужому проекту сбора при смене пользователя в приложении

### ISSUE THREAD

**Issue by eduard-kazakov** [nextgis/nextgiscollector_android#15]
Последовательность действий:
1. Создаём проект сбора №1, назначаем в него сборщика A.
2. Создаём проект сбора №2, назначаем в него сборщика Б.
3. Логинимся в приложении как сборщик А, входим в проект №1, собираем.
4. Разлогиниваемся, входим как сборщик Б, по умолчанию продолжаем видеть проект №1, и даже можем в нем что-то поделать. В меню смены проекта доступен при этом только проект №2. Если переключились, в №1 уже не вернуться.

**Comment by simgislab** [comment]
то есть 4. разлогиниваемся, но из проекта №1 не выходим?

**Comment by simgislab** [comment]
Проверил. Подтверждаю.

После выхода из аккаунта выхода из проекта не происходит. Можно заходить с любым другим аккаунтом и останешься в том проекте который был до выхода.
