### ISSUE TITLE
Приложение не показывает растровые стили

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgiscollector_android#6]
Год назад показывало

**Comment by 4eRTuk** [comment]
Имеешь ввиду для векторных слоев которые из облака? Или просто растровые ТМС слои?

**Comment by trolleway** [comment]
те которые "cls": "qgis_vector_style" http://trolleway.nextgis.com/resource/72/json

**Comment by simgislab** [comment]
Возможно проблема на стороне @karavanjo 

Растровый слой (стиль) просто нельзя добавить, он не выбирается

**Comment by 4eRTuk** [comment]
@Romchik93 в итоге заработало или по-прежнему какие-то слои у тебя не показываются?

**Comment by Romchik93** [comment]
@4eRTuk работает
